language: python

python:
  - "3.6"
  - "3.7"

install:
  - travis_wait 30 mvn install
  - pip install -r requirements.txt

script:
  - coverage run unittest_tests.py -v

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
